version: '3'

services:
  api:
    build: .
    restart: always
    privileged: true
    environment:
      - ADMIN_PATH
      - DATABASE_CLIENT
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - NODE_ENV
    ports:
      - 1337:1337
    volumes:
      - ./app:/usr/src/api/app
      # - /usr/src/api/app/node_modules
